
USE ECommerceDB
GO

ALTER TABLE PRODUSE
    ADD CONSTRAINT FK_PRODUSE_CATEGORII FOREIGN KEY (IdCateg)
    REFERENCES CATEGORII(IdCateg)
GO

ALTER TABLE STOC_DEPOZIT
    ADD CONSTRAINT FK_STOC_PRODUSE FOREIGN KEY (IdProdus)
    REFERENCES PRODUSE(IdProdus)
GO

ALTER TABLE STOC_DEPOZIT
    ADD CONSTRAINT FK_STOC_DEPOZITE FOREIGN KEY (IdDepozit)
    REFERENCES DEPOZITE(IdDepozit)
GO

ALTER TABLE COMENZI
    ADD CONSTRAINT FK_COMENZI_CLIENTI FOREIGN KEY (IdClient)
    REFERENCES CLIENTI(IdClient)
GO

ALTER TABLE DETALII_COMANDA
    ADD CONSTRAINT FK_DETALII_COMENZI FOREIGN KEY (IdComanda)
    REFERENCES COMENZI(IdComanda)
GO

ALTER TABLE DETALII_COMANDA
    ADD CONSTRAINT FK_DETALII_PRODUSE FOREIGN KEY (IdProdus)
    REFERENCES PRODUSE(IdProdus)
GO

ALTER TABLE DETALII_COMANDA
    ADD CONSTRAINT FK_DETALII_DEPOZITE FOREIGN KEY (IdDepozit)
    REFERENCES DEPOZITE(IdDepozit)
GO